Transform: AWS::Serverless-2016-10-31

Resources:
  JsonnetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: python3.6
      CodeUri: ./src
      # Policies:
      #   - S3ReadPolicy:
      #       BucketName: ...

  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: Jsonnet
      Description: Process CloudFormation template using Jsonnet
      FunctionName: !GetAtt JsonnetFunction.Arn

